### ISSUE TITLE
chain_demo.py result error?

### ISSUE THREAD

**Issue by codylcs** [aharley/pips#11]
to make sure result trustworthy, i change (x,y) coordinate in chain_demo.py like this
```
x = torch.ones((1, N), device=torch.device('cuda')) * 394.0
y = torch.ones((1, N), device=torch.device('cuda')) * 93.0
```
the gifs generated in root/ as flowing，chain_out_1.gif looks good,but chain_out_2.gif and chain_out_3.gif seems wrong,
what should i do to get right result? please
chain_out_1.gif
![chain_out_1](https://user-images.githubusercontent.com/48380363/209046853-4712efc2-63df-4de3-98fd-e6b4956539d8.gif)
chain_out_2.gif
![chain_out_2](https://user-images.githubusercontent.com/48380363/209046753-7b8993a7-61f8-4f07-8cb2-7dc9b9d95741.gif)
chain_out_3.gif
![chain_out_3](https://user-images.githubusercontent.com/48380363/209046883-c62324aa-41bb-462a-819c-e76fead3ab35.gif)

**Comment by aharley** [comment]
This is a great test, and I think you did it correctly. Some points are harder to track than others, and what you are seeing here is simply success/failure of the current model.

**Comment by codylcs** [comment]
thanks for reply, how to optimize further if i want apply the model in my situation?

**Comment by aharley** [comment]
The simplest thing is: if you have access to some synthetic data that looks like your target data, finetune the model on that data. For example, if you want the model to excel at tracking dogs, you can train it on dogs. Right now it's more of a general-purpose machine, and making it 100% reliable is an open research problem.

**Comment by codylcs** [comment]
> The simplest thing is: if you have access to some synthetic data that looks like your target data, finetune the model on that data. For example, if you want the model to excel at tracking dogs, you can train it on dogs. Right now it's more of a general-purpose machine, and making it 100% reliable is an open research problem.
yeah,100% reliable is an open research problem,https://github.com/deepmind/tapnet/issues/7#issuecomment-1361243826 should also can not agree with any more,thanks all u guys
