### ISSUE TITLE
Is PIPs an online or offline method?

### ISSUE THREAD

**Issue by HarryHsing** [aharley/pips#12]
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/36613867/210503805-4636599c-c178-4d4c-82e2-15ea4b396fbe.png">

Thank you very much for your amazing work!

 I do not see temporal information exchange/combination inside the red box area. Thus, I wonder if PIPs is an online method or not.

**Comment by aharley** [comment]
The `T` part of the shape `(T,D)` is timesteps, and the MLPMixer has some parameters on this axis, so lots of information is combined/exchanged there.

If your `T` timesteps end in timestep `t`, then you can call it online. The paper and repo are more in the "offline" style though, where we assume the full video is stored on disk and we can process it as we like.

**Comment by HarryHsing** [comment]
> The `T` part of the shape `(T,D)` is timesteps, and the MLPMixer has some parameters on this axis, so lots of information is combined/exchanged there.
> 
> 
> 
> If your `T` timesteps end in timestep `t`, then you can call it online. The paper and repo are more in the "offline" style though, where we assume the full video is stored on disk and we can process it as we like. 

Got it! Thank you very much for your kind support!
