### ISSUE TITLE
Why is the model able to track a point that moves beyond its neighbor P · P patch?

### ISSUE THREAD

**Issue by ZHAOZHIHAO** [aharley/pips#18]
Hi,

If I understand correctly, the MLP mixer receives the correspondence score of the point's P · P neighbors and P=3*2+1=7 in the experiments. But sometimes the points moves much more than 3 pixels between two adjacent frames and the model is still able to roughly track it. Do you have any hypotheses that how does the model know where the point goes in this situation?  

Best

**Comment by aharley** [comment]
It's PxP in multiple scales. The coarser scales enable us to capture fast motion.

**Comment by ZHAOZHIHAO** [comment]
Thank you. That makes perfect sense. Just like why we have pyramid in optical flow methods.
