### ISSUE TITLE
Question about the evaluation on BADJA

### ISSUE THREAD

**Issue by qianduoduolr** [aharley/pips#19]
Hi, I have a problem with the evaluation on BADJA.
The paper said, "Here, we focus on the harder setting, where the ground-truth mask is unknown". What does it mean? If we do not have the gt mask? How do we compute the PCK-T?

**Comment by aharley** [comment]
The idea is to avoid using the mask as an input to the model, which would be the standard practice in mask propagation methods. You are right that the mask is used for PCK-T computation.
