### ISSUE TITLE
Hosting weights and a demo on Hugging Face

### ISSUE THREAD

**Issue by NimaBoscarino** [aharley/pips#2]
Hello, and congratulations on getting accepted for ECCV 2022! It would be really cool to have the model available on the Hugging Face Hub, and I'm sure folks would also love to play around with a demo.

I'm more than happy to help out with that if it's something you're interested in! I know that a demo would ideally need a GPU, so I can also look into sourcing one for you. Let me know what you think!

**Comment by aharley** [comment]
Sure, if we do it together maybe it will be easy! Maybe you can email me at my aharley -at- cs.stanford.edu email, with a bit more info?

**Comment by hangg7** [comment]
Thumbs up for the idea, and having a pretrained model will make playing with your method much easier!

**Comment by NimaBoscarino** [comment]
Awesome! Sounds good, I'll send an email over to you 😄
