### ISSUE TITLE
Sequence loss

### ISSUE THREAD

**Issue by npmhung** [aharley/pips#23]
In the sequence loss function, there are visible and valid arrays for each video sequence. However, only the valid is used to calculate the loss. I would like to know what does the valid array represent for each video?

**Comment by aharley** [comment]
`valid` represents: for each timestep, is the annotation in `trajs_g` valid or not?

For a while I experimented with using `vis` in the mask too (so that we only apply loss on timesteps where the target is visible), but `valid` seemed to be enough.
