### ISSUE TITLE
Feature representation not locked in test-time trajectory linking?

### ISSUE THREAD

**Issue by ZHAOZHIHAO** [aharley/pips#24]
Hi,

Section 3.7 of the paper says "To lock the model into tracking the “original” target, we simply re-use the original F0 across all re-initializations."

But in chain_demo.py, the query point's feature representation seems not locked?
```
line 54  outs = model(traj_e[:,cur_frame].reshape(1, -1, 2), rgb_seq, iters=6, feat_init=feat_init, return_feat=True)
line 57  feat_init = outs[3]
```

Best

**Comment by HarryHsing** [comment]
Hi, it will always be fixed on the initial **ffeat**, you may confuse it with **ffeats**

https://github.com/aharley/pips/blob/bde038a837c0ca94ad4c10748e57d7a3322565ac/nets/pips.py#L463

https://github.com/aharley/pips/blob/bde038a837c0ca94ad4c10748e57d7a3322565ac/nets/pips.py#L609

The return term in L609 is ffeat, not ffeats.

**Comment by ZHAOZHIHAO** [comment]
Thanks, you are right. I did confuse it with feats.
