### ISSUE TITLE
Should it be "x / div_term", not "x * div_term"?

### ISSUE THREAD

**Issue by ZHAOZHIHAO** [aharley/pips#30]
Hi,

For the position embedding (the get_3d_embedding function in misc.py), should it be "x / div_term", not "x * div_term"? 

```
    div_term = (torch.arange(0, C, 2, device=xyz.device, dtype=torch.float32) * (1000.0 / C)).reshape(1, 1, int(C/2))
    pe_x[:, :, 0::2] = torch.sin(x * div_term)
```

Best

**Comment by aharley** [comment]
I think you are right. Have you found any interesting effects after fixing this in your version?

**Comment by ZHAOZHIHAO** [comment]
It seems that after fixing this issue, the tracking result is better for long videos, like after 200/300 frames. Without fixing this, the tracking result may be sometimes wrong for 1 frame. Also, it seems helpful to track a point that is on a small object.
