### ISSUE TITLE
How do you extract only the point trajectories of an object in the demo?

### ISSUE THREAD

**Issue by bevisxia520** [aharley/pips#31]
Hello, thank you very much for your work. I've also learned a lot from your work. But I have some questions after watching the demo you provided. How do you take a picture of, say, many fish and simply extract all the points in one fish to produce point trajectories. I would appreciate it if you could provide some code and ideas for this. Looking forward to your reply.

**Comment by aharley** [comment]
That visualization uses the DAVIS dataset, where RGB videos are paired with binary masks for some objects. We use the object mask to specify which coordinates to track. If you want to produce something similar in a dataset without masks, you could use an object detector and segmenter, like Mask-RCNN, or maybe SAM (the Segment Anything Model).
