### ISSUE TITLE
Demo.py not running as expected

### ISSUE THREAD

**Issue by Akshajy6** [aharley/pips#34]
Hi @aharley, I love your work and am trying to use it to track particles across videos for a project. However, when I cloned the repo, installed the packages in requirements.txt, and tried to run demo.py, I get both a KeyError and OSError.
Here is the entire terminal output:
![image](https://github.com/aharley/pips/assets/65787186/dac4f8b1-5afd-4371-8817-fdbd9c7c6790)
![image](https://github.com/aharley/pips/assets/65787186/a1831727-fa59-4eb9-85e3-fe0e639128ac)

From looking at this output and the demo.py file, it looks to me like both the print statements on lines 96 and 107 print the expected output, but my guess is that the log_dir parameter of SummaryWriter on line 110 is causing the errors. I would really appreciate any advice on how to fix this error so demo.py runs correctly.

**Comment by aharley** [comment]
I see! Looks like you are running this on windows. Do you have access to a unix machine you could try this on?

Anyway, if you're lucky, this might be easy to fix. Windows does not like colons. So, try deleting this line:

`model_name = model_name + '_' + model_date`

(since `model_date` has a colon inside it)

**Comment by riponazad** [comment]
> I see! Looks like you are running this on windows. Do you have access to a unix machine you could try this on?
> 
> Anyway, if you're lucky, this might be easy to fix. Windows does not like colons. So, try deleting this line:
> 
> `model_name = model_name + '_' + model_date`
> 
> (since `model_date` has a colon inside it)

it worked.
