### ISSUE TITLE
Instruction to trian PiPs++

### ISSUE THREAD

**Issue by jytime** [aharley/pips#38]
Hi Adam,

Thank you for sharing this excellent work. I am interested in using PiPs++ for a project and noticed that there are files already available, such as train2.py. Could you please clarify whether these files are complete? Additionally, would it be possible to get some instructions or documentation on how to train a PiPs++ model?

Best,
Jianyuan

**Comment by bhack** [comment]
https://github.com/aharley/pips/issues/37#issuecomment-1705987475

**Comment by bhack** [comment]
https://github.com/aharley/pips2
