### ISSUE TITLE
Error running demo

### ISSUE THREAD

**Issue by greeneggsandyaml** [aharley/pips#4]
Hello, thanks for your nice paper. When I try to run the demo, I get:

```
>>> python demo.py

filenames ['./demo_images/000100.jpg', './demo_images/000101.jpg', './demo_images/000102.jpg', './demo_images/000103.jpg', './demo_images/000104.jpg', './demo_images/000105.jpg', './demo_images/000106.jpg', './demo_images/000107.jpg', './demo_images/000108.jpg', './demo_images/000109.jpg', './demo_images/000110.jpg', './demo_images/000111.jpg', './demo_images/000112.jpg', './demo_images/000113.jpg', './demo_images/000114.jpg', './demo_images/000115.jpg', './demo_images/000116.jpg', './demo_images/000117.jpg', './demo_images/000118.jpg', './demo_images/000119.jpg', './demo_images/000120.jpg', './demo_images/000121.jpg', './demo_images/000122.jpg', './demo_images/000123.jpg', './demo_images/000124.jpg', './demo_images/000125.jpg', './demo_images/000126.jpg', './demo_images/000127.jpg', './demo_images/000128.jpg', './demo_images/000129.jpg', './demo_images/000130.jpg', './demo_images/000131.jpg', './demo_images/000132.jpg', './demo_images/000133.jpg', './demo_images/000134.jpg', './demo_images/000135.jpg', './demo_images/000136.jpg', './demo_images/000137.jpg', './demo_images/000138.jpg', './demo_images/000139.jpg', './demo_images/000140.jpg', './demo_images/000141.jpg', './demo_images/000142.jpg', './demo_images/000143.jpg', './demo_images/000144.jpg', './demo_images/000145.jpg', './demo_images/000146.jpg', './demo_images/000147.jpg', './demo_images/000148.jpg', './demo_images/000149.jpg', './demo_images/000150.jpg', './demo_images/000151.jpg', './demo_images/000152.jpg', './demo_images/000153.jpg', './demo_images/000154.jpg', './demo_images/000155.jpg', './demo_images/000156.jpg', './demo_images/000157.jpg', './demo_images/000158.jpg', './demo_images/000159.jpg', './demo_images/000160.jpg', './demo_images/000161.jpg', './demo_images/000162.jpg', './demo_images/000163.jpg', './demo_images/000164.jpg', './demo_images/000165.jpg', './demo_images/000166.jpg', './demo_images/000167.jpg', './demo_images/000168.jpg', './demo_images/000169.jpg', './demo_images/000170.jpg', './demo_images/000171.jpg', './demo_images/000172.jpg', './demo_images/000173.jpg', './demo_images/000174.jpg', './demo_images/000175.jpg', './demo_images/000176.jpg', './demo_images/000177.jpg', './demo_images/000178.jpg', './demo_images/000179.jpg', './demo_images/000180.jpg', './demo_images/000181.jpg', './demo_images/000182.jpg', './demo_images/000183.jpg', './demo_images/000184.jpg', './demo_images/000185.jpg', './demo_images/000186.jpg', './demo_images/000187.jpg', './demo_images/000188.jpg', './demo_images/000189.jpg', './demo_images/000190.jpg', './demo_images/000191.jpg', './demo_images/000192.jpg', './demo_images/000193.jpg', './demo_images/000194.jpg', './demo_images/000195.jpg', './demo_images/000196.jpg', './demo_images/000197.jpg', './demo_images/000198.jpg', './demo_images/000199.jpg']
model_name 01_8_256_00_08:34:33
reading ckpt from reference_model
...found checkpoint reference_model/model-000100000.pth
Traceback (most recent call last):
  File "/my/home/pips/demo.py", line 166, in <module>
    main()
  File "/my/home/pips/demo.py", line 121, in main
    _ = saverloader.load(init_dir, model)
  File "/my/home/pips/saverloader.py", line 59, in load
    model.load_state_dict(checkpoint['model_state_dict'], strict=False)
  File "/my/home/opt/miniconda3/envs/new/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1497, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Pips:
	size mismatch for delta_block.to_delta.0.weight: copying a param with shape torch.Size([512, 715]) from checkpoint, the shape in current model is torch.Size([512, 1038]).
```

I have only run `sh get_reference_model.sh` and I have not changed any files. 

Thanks for your help!

**Comment by aharley** [comment]
Ok! 715 is the right number of channels there, so I don't know where 1038 is coming from. Can you add these prints to the `forward` function of `DeltaBlock` in `pips.py`, and let me know what you get?
```
print('fhid', fhid.shape)
print('fcorr', fcorr.shape)
print('flow_sincos', flow_sincos.shape)
```

For me, it shows:
```
fhid torch.Size([256, 8, 128])
fcorr torch.Size([256, 8, 392])
flow_sincos torch.Size([256, 8, 195])
```

**Comment by codylcs** [comment]
reading ckpt from reference_model
...found checkpoint reference_model\model-000200000.pth
Traceback (most recent call last):
  File "F:\pycharmProjs\pips-main\chain_demo.py", line 195, in <module>
    main()
  File "F:\pycharmProjs\pips-main\chain_demo.py", line 151, in main
    _ = saverloader.load(init_dir, model)
  File "F:\pycharmProjs\pips-main\saverloader.py", line 59, in load
    model.load_state_dict(checkpoint['model_state_dict'], strict=False)
  File "E:\ProgramData\Anaconda3\envs\pips\lib\site-packages\torch\nn\modules\module.py", line 1604, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Pips:
	size mismatch for delta_block.to_delta.0.weight: copying a param with shape torch.Size([512, 519]) from checkpoint, the shape in current model is torch.Size([512, 715]).

**Comment by codylcs** [comment]
> Ok! 715 is the right number of channels there, so I don't know where 1038 is coming from. Can you add these prints to the `forward` function of `DeltaBlock` in `pips.py`, and let me know what you get?
> 
> ```
> print('fhid', fhid.shape)
> print('fcorr', fcorr.shape)
> print('flow_sincos', flow_sincos.shape)
> ```
> 
> For me, it shows:
> 
> ```
> fhid torch.Size([256, 8, 128])
> fcorr torch.Size([256, 8, 392])
> flow_sincos torch.Size([256, 8, 195])
> ```

please checkout the way that prints in forward is wright or not,i can load model right, then how to forward?

**Comment by aharley** [comment]
Hi @codylcs, sorry, I am updating the repo a bit tonight, and I added a new model ckpt. Can you pull again? I think your issue will disappear.

**Comment by codylcs** [comment]
> 715

i print k and  relative shape,
...found checkpoint reference_model\model-000200000.pth
delta_block.to_delta.0.weight torch.Size([512, 519])
model k: torch.Size([512, 715])
as u see,mode net shapes are not same as parameters shape

**Comment by codylcs** [comment]
> Hi @codylcs, sorry, I am updating the repo a bit tonight, and I added a new model ckpt. Can you pull again? I think your issue will disappear.

yeah ，thanks
