### ISSUE TITLE
In Windows system, the Tensorboad SummaryWriter() would throw an OSError ([WinError 123])

### ISSUE THREAD

**Issue by rishi-a** [aharley/pips#5]
*Update*
The error is resolved by renaming the model. In particular, the model name should not have the `datetime.datetime.now()` string else the `SummaryWriter()` throws an error. 

TLDR:
Resolution: Rename line 106 to `model_date = "Today"` or any other string except the `datetime.datetime.now().strftime('%H:%M:%S')`

**Comment by aharley** [comment]
Thanks! That makes sense. I think Windows does not like special characters in folder/file names.
